services:
  - type: web
    name: weather-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      gunicorn weatherproject.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: weatherproject.settings
      - key: PYTHON_VERSION
        value: 3.12
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com

staticAssets:
  - type: static
    name: staticfiles
    buildCommand: |
      python manage.py collectstatic --noinput
    staticPublishPath: staticfiles
